# Generated by Django 4.0.2 on 2022-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('duplicate', models.BooleanField(default=True)),
            ],
        ),
    ]
